### PR TITLE
之前说段错误是我的锅，我把旧的obj文件拿去链接了。

### PR DESCRIPTION
**Pull request by linux40**
还有，不算24小时以内的提交的话，我的这个规则在`Note`下没有把所有地方标记出来，`Warning`下可以，而且都是在`'*,-GJB-rule-1.1.1'`下跑的，选`'*,-GJB-rule-1.2.1'`不行，而且`'*,-GJB-rule-1.1.1'`还进行了`'*,-GJB-rule-1.1.16'`的规则检查。

当然，新版本怎么样都是段错误。。。

对了我本地的代码，`GJBModule.cpp`是把有`Finder`的行都删了的，提交上来怎么都有了呢。。。可能有误操作。

### CODE REVIEW

**Comment by lszero** [comment]
1. If DiagnosticIDs::Warning works OK, so DiagnosticIDs::Note does, they are just DiagnosticIDs::Level. BTW, not all SourceLocation will be marked if they located at the same place.

2. '*,-GJB-rule-1.1.1' means enable all checks expect GJB-rule-1.1.1.
If you wanna enable GJB-rule-1.1.1 only, using "-check=GJB-rule-1.1.1".

3. I have no segment fault in my MacOS platform. Why I push incomplete code to github? 
If you still have this error, plz email me the detail info.

**Comment by lszero** [comment]
Of course it won’t have any results, because ‘-‘ prefix will disable checks. If you want to run some checks, remove ‘-‘ prefix.

**Comment by linux40** [comment]
眼神不好。。。对了Note单独不显示的，不过Remark会显示，在本地改成了Remark，暂时没提交。至于这个pull request，最后再合并就行了。。。

**Comment by lszero** [comment]
Preprocessor interface already exists. See `registerPPCallbacks()`.

**Pull request closed without merging**
